alias ExVEx.Packaging.Zip
alias ExVEx.Packaging.Zip.Entry

prolog = ~s(<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n)

parts = [
  {"[Content_Types].xml",
   prolog <>
     ~s(<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/><Override PartName="/xl/tables/table1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml"/></Types>)},
  {"_rels/.rels",
   prolog <>
     ~s(<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>)},
  {"xl/workbook.xml",
   prolog <>
     ~s(<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x15 xr xr6 xr10 xr2" xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision" xmlns:xr6="http://schemas.microsoft.com/office/spreadsheetml/2016/revision6" xmlns:xr10="http://schemas.microsoft.com/office/spreadsheetml/2016/revision10" xmlns:xr2="http://schemas.microsoft.com/office/spreadsheetml/2015/revision2"><fileVersion appName="xl" lastEdited="7" lowestEdited="7" rupBuild="27425"/><workbookPr defaultThemeVersion="166925"/><bookViews><workbookView xWindow="0" yWindow="0" windowWidth="28800" windowHeight="16380" xr2:uid="{00000000-000D-0000-FFFF-FFFF00000000}"/></bookViews><sheets><sheet name="Sales" sheetId="1" r:id="rId1"/><sheet name="Summary" sheetId="2" r:id="rId2"/></sheets><definedNames><definedName name="GrandTotal">SUM\(Orders[Amount]\)</definedName></definedNames><calcPr calcId="191029"/></workbook>)},
  {"xl/_rels/workbook.xml.rels",
   prolog <>
     ~s(<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>)},
  {"xl/worksheets/sheet1.xml",
   prolog <>
     ~s(<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x14ac xr xr2 xr3" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision" xmlns:xr2="http://schemas.microsoft.com/office/spreadsheetml/2015/revision2" xmlns:xr3="http://schemas.microsoft.com/office/spreadsheetml/2016/revision3" xr:uid="{00000000-0001-0000-0000-000000000000}"><dimension ref="A1:D5"/><sheetViews><sheetView tabSelected="1" workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="14.4" x14ac:dyDescent="0.3"/><cols><col min="1" max="4" width="12.6640625" customWidth="1"/></cols><sheetData><row r="1" spans="1:4" x14ac:dyDescent="0.3"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="s"><v>2</v></c><c r="D1" t="s"><v>3</v></c></row><row r="2" spans="1:4" x14ac:dyDescent="0.3"><c r="A2" t="s"><v>4</v></c><c r="B2"><v>2</v></c><c r="C2"><v>10.5</v></c><c r="D2"><f>Orders[[#This Row],[Qty]]*Orders[[#This Row],[Amount]]</f><v>21</v></c></row><row r="3" spans="1:4" x14ac:dyDescent="0.3"><c r="A3" t="s"><v>5</v></c><c r="B3"><v>3</v></c><c r="C3"><v>20</v></c><c r="D3"><f>Orders[[#This Row],[Qty]]*Orders[[#This Row],[Amount]]</f><v>60</v></c></row><row r="4" spans="1:4" x14ac:dyDescent="0.3"><c r="A4" t="s"><v>6</v></c><c r="B4"><v>1</v></c><c r="C4"><v>5.25</v></c><c r="D4"><f>Orders[[#This Row],[Qty]]*Orders[[#This Row],[Amount]]</f><v>5.25</v></c></row><row r="5" spans="1:4" x14ac:dyDescent="0.3"><c r="A5" t="s"><v>7</v></c><c r="C5"><f>SUBTOTAL\(109,Orders[Amount]\)</f><v>35.75</v></c><c r="D5"><f>SUBTOTAL\(109,Orders[Total]\)</f><v>86.25</v></c></row></sheetData><pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/><tableParts count="1"><tablePart r:id="rId1"/></tableParts></worksheet>)},
  {"xl/worksheets/_rels/sheet1.xml.rels",
   prolog <>
     ~s(<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="../tables/table1.xml"/></Relationships>)},
  {"xl/worksheets/sheet2.xml",
   prolog <>
     ~s(<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><dimension ref="A1:B2"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="14.4"/><sheetData><row r="1" spans="1:2"><c r="A1" t="s"><v>8</v></c><c r="B1"><f>SUM\(Orders[Amount]\)</f><v>35.75</v></c></row><row r="2" spans="1:2"><c r="A2" t="s"><v>9</v></c><c r="B2"><f>COUNTA\(Orders[Region]\)</f><v>3</v></c></row></sheetData><pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/></worksheet>)},
  {"xl/tables/table1.xml",
   prolog <>
     ~s(<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="xr xr3" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision" xmlns:xr3="http://schemas.microsoft.com/office/spreadsheetml/2016/revision3" id="1" xr:uid="{00000000-000C-0000-FFFF-FFFF00000000}" name="Orders" displayName="Orders" ref="A1:D5" totalsRowCount="1"><autoFilter ref="A1:D4" xr:uid="{00000000-0009-0000-0100-000001000000}"/><tableColumns count="4"><tableColumn id="1" xr3:uid="{00000000-0010-0000-0100-000001000000}" name="Region" totalsRowLabel="Total"/><tableColumn id="2" xr3:uid="{00000000-0010-0000-0100-000002000000}" name="Qty"/><tableColumn id="3" xr3:uid="{00000000-0010-0000-0100-000003000000}" name="Amount" totalsRowFunction="sum"/><tableColumn id="4" xr3:uid="{00000000-0010-0000-0100-000004000000}" name="Total" totalsRowFunction="sum"><calculatedColumnFormula>Orders[[#This Row],[Qty]]*Orders[[#This Row],[Amount]]</calculatedColumnFormula></tableColumn></tableColumns><tableStyleInfo name="TableStyleMedium2" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/></table>)},
  {"xl/sharedStrings.xml",
   prolog <>
     ~s(<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="12" uniqueCount="10"><si><t>Region</t></si><si><t>Qty</t></si><si><t>Amount</t></si><si><t>Total</t></si><si><t>North</t></si><si><t>South</t></si><si><t>East</t></si><si><t>Total</t></si><si><t>Revenue</t></si><si><t>Regions</t></si></sst>)},
  {"xl/styles.xml",
   prolog <>
     ~s(<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Calibri"/><family val="2"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleLight16"/></styleSheet>)},
  {"xl/theme/theme1.xml",
   prolog <>
     ~s(<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Office Theme"><a:themeElements><a:clrScheme name="Office"><a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1><a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1></a:clrScheme></a:themeElements></a:theme>)}
]

entries = Enum.map(parts, fn {path, data} -> %Entry{path: path, data: data} end)
:ok = Zip.write(Path.expand("../fixtures/with_table.xlsx", __DIR__), entries)
IO.puts("wrote with_table.xlsx")
